name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        go-versions: ['1.22', '1.21']
        platform: [self-hosted]
        environment-variables: [build/config/plain.sh, build/config/libpfm4.sh, build/config/libipmctl.sh]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-versions }}
        check-latest: true
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run presubmit checks
      run: |
        source ${{ matrix.environment-variables }}
        if [[ "${BUILD_PACKAGES}" != "" ]]; then sudo apt-get -y update; sudo apt-get install pkg-config python3; fi
        make -e presubmit
    - name: Run tests
      env:
        GOLANG_VERSION: ${{ matrix.go-versions }}
      run: |
        source ${{ matrix.environment-variables }}
        make test
  test-integration:
    strategy:
      matrix:
        go-versions: ['1.22', '1.21']
        platform: [self-hosted]
        environment-variables: [build/config/plain.sh, build/config/libpfm4.sh, build/config/libipmctl.sh]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run integration tests
      env:
        GOLANG_VERSION: ${{ matrix.go-versions }}
      run: |
        set -ex
        source ${{ matrix.environment-variables }}
        make docker-test-integration
    - name: Upload cAdvisor log file
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cadvisor.log
        path: ${{ github.workspace }}/go/src/github.com/google/cadvisor/cadvisor.log
